import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { Order } from '@/lib/types';

export default function AdminOrders() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { const loadOrders = async () => { const { data } = await supabase.from('orders').select('*').order('created_at', { ascending: false }); setOrders((data as Order[] | null) ?? []); setLoading(false); }; void loadOrders(); }, []);
  return <div className="p-6 max-w-6xl mx-auto"><div className="mb-8"><h1 className="text-2xl font-bold text-gray-900">Orders</h1><p className="text-gray-500 mt-1">Purchases made in the marketplace.</p></div><div className="bg-white border border-gray-200 rounded-xl overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 border-b border-gray-200"><tr><th className="px-5 py-3 font-semibold text-gray-600">Order</th><th className="px-5 py-3 font-semibold text-gray-600">Customer</th><th className="px-5 py-3 font-semibold text-gray-600">Total</th><th className="px-5 py-3 font-semibold text-gray-600">Status</th><th className="px-5 py-3 font-semibold text-gray-600">Date</th></tr></thead><tbody className="divide-y divide-gray-100">{loading ? <tr><td colSpan={5} className="px-5 py-10 text-center text-gray-400">Loading orders...</td></tr> : orders.length === 0 ? <tr><td colSpan={5} className="px-5 py-10 text-center text-gray-400">No orders have been placed yet.</td></tr> : orders.map((order) => <tr key={order.id} className="hover:bg-gray-50"><td className="px-5 py-4 font-mono text-xs text-gray-600">{order.id.slice(0, 8)}</td><td className="px-5 py-4 font-mono text-xs text-gray-500">{order.user_id.slice(0, 8)}</td><td className="px-5 py-4 text-gray-600">${Number(order.total).toFixed(2)}</td><td className="px-5 py-4"><span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-700">{order.status}</span></td><td className="px-5 py-4 text-gray-500">{new Date(order.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>;
}
